services:

  # crm:
  #   container_name: crm
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5332/customers
  #     SPRING_DATASOURCE_USERNAME: shuaibu
  #     SPRING_DATASOURCE_PASSWORD: password
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: shuaibu
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432" 
    restart: unless-stopped
#     networks:
#       - crm-network

# networks:
#     crm-network:
#         driver: bridge


volumes:
  db:
